/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IEvaluationClientApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Returns an overview of the currently active task for a run.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>ApiClientTaskTemplateInfo</returns>
        ApiClientTaskTemplateInfo GetApiV2ClientEvaluationCurrentTaskByEvaluationId (string evaluationId, string session = null);

        /// <summary>
        /// Returns an overview of the currently active task for a run.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>ApiResponse of ApiClientTaskTemplateInfo</returns>
        ApiResponse<ApiClientTaskTemplateInfo> GetApiV2ClientEvaluationCurrentTaskByEvaluationIdWithHttpInfo (string evaluationId, string session = null);
        /// <summary>
        /// Lists an overview of all evaluation runs visible to the current client.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>List&lt;ApiClientEvaluationInfo&gt;</returns>
        List<ApiClientEvaluationInfo> GetApiV2ClientEvaluationList (string session = null);

        /// <summary>
        /// Lists an overview of all evaluation runs visible to the current client.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>ApiResponse of List&lt;ApiClientEvaluationInfo&gt;</returns>
        ApiResponse<List<ApiClientEvaluationInfo>> GetApiV2ClientEvaluationListWithHttpInfo (string session = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Returns an overview of the currently active task for a run.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>Task of ApiClientTaskTemplateInfo</returns>
        System.Threading.Tasks.Task<ApiClientTaskTemplateInfo> GetApiV2ClientEvaluationCurrentTaskByEvaluationIdAsync (string evaluationId, string session = null);

        /// <summary>
        /// Returns an overview of the currently active task for a run.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>Task of ApiResponse (ApiClientTaskTemplateInfo)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiClientTaskTemplateInfo>> GetApiV2ClientEvaluationCurrentTaskByEvaluationIdAsyncWithHttpInfo (string evaluationId, string session = null);
        /// <summary>
        /// Lists an overview of all evaluation runs visible to the current client.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>Task of List&lt;ApiClientEvaluationInfo&gt;</returns>
        System.Threading.Tasks.Task<List<ApiClientEvaluationInfo>> GetApiV2ClientEvaluationListAsync (string session = null);

        /// <summary>
        /// Lists an overview of all evaluation runs visible to the current client.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;ApiClientEvaluationInfo&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ApiClientEvaluationInfo>>> GetApiV2ClientEvaluationListAsyncWithHttpInfo (string session = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class EvaluationClientApi : IEvaluationClientApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EvaluationClientApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EvaluationClientApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EvaluationClientApi"/> class
        /// </summary>
        /// <returns></returns>
        public EvaluationClientApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EvaluationClientApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EvaluationClientApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Returns an overview of the currently active task for a run. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>ApiClientTaskTemplateInfo</returns>
        public ApiClientTaskTemplateInfo GetApiV2ClientEvaluationCurrentTaskByEvaluationId (string evaluationId, string session = null)
        {
             ApiResponse<ApiClientTaskTemplateInfo> localVarResponse = GetApiV2ClientEvaluationCurrentTaskByEvaluationIdWithHttpInfo(evaluationId, session);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns an overview of the currently active task for a run. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>ApiResponse of ApiClientTaskTemplateInfo</returns>
        public ApiResponse< ApiClientTaskTemplateInfo > GetApiV2ClientEvaluationCurrentTaskByEvaluationIdWithHttpInfo (string evaluationId, string session = null)
        {
            // verify the required parameter 'evaluationId' is set
            if (evaluationId == null)
                throw new ApiException(400, "Missing required parameter 'evaluationId' when calling EvaluationClientApi->GetApiV2ClientEvaluationCurrentTaskByEvaluationId");

            var localVarPath = "/api/v2/client/evaluation/currentTask/{evaluationId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (evaluationId != null) localVarPathParams.Add("evaluationId", this.Configuration.ApiClient.ParameterToString(evaluationId)); // path parameter
            if (session != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "session", session)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2ClientEvaluationCurrentTaskByEvaluationId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiClientTaskTemplateInfo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiClientTaskTemplateInfo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiClientTaskTemplateInfo)));
        }

        /// <summary>
        /// Returns an overview of the currently active task for a run. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>Task of ApiClientTaskTemplateInfo</returns>
        public async System.Threading.Tasks.Task<ApiClientTaskTemplateInfo> GetApiV2ClientEvaluationCurrentTaskByEvaluationIdAsync (string evaluationId, string session = null)
        {
             ApiResponse<ApiClientTaskTemplateInfo> localVarResponse = await GetApiV2ClientEvaluationCurrentTaskByEvaluationIdAsyncWithHttpInfo(evaluationId, session);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns an overview of the currently active task for a run. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>Task of ApiResponse (ApiClientTaskTemplateInfo)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiClientTaskTemplateInfo>> GetApiV2ClientEvaluationCurrentTaskByEvaluationIdAsyncWithHttpInfo (string evaluationId, string session = null)
        {
            // verify the required parameter 'evaluationId' is set
            if (evaluationId == null)
                throw new ApiException(400, "Missing required parameter 'evaluationId' when calling EvaluationClientApi->GetApiV2ClientEvaluationCurrentTaskByEvaluationId");

            var localVarPath = "/api/v2/client/evaluation/currentTask/{evaluationId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (evaluationId != null) localVarPathParams.Add("evaluationId", this.Configuration.ApiClient.ParameterToString(evaluationId)); // path parameter
            if (session != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "session", session)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2ClientEvaluationCurrentTaskByEvaluationId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiClientTaskTemplateInfo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiClientTaskTemplateInfo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiClientTaskTemplateInfo)));
        }

        /// <summary>
        /// Lists an overview of all evaluation runs visible to the current client. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>List&lt;ApiClientEvaluationInfo&gt;</returns>
        public List<ApiClientEvaluationInfo> GetApiV2ClientEvaluationList (string session = null)
        {
             ApiResponse<List<ApiClientEvaluationInfo>> localVarResponse = GetApiV2ClientEvaluationListWithHttpInfo(session);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Lists an overview of all evaluation runs visible to the current client. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>ApiResponse of List&lt;ApiClientEvaluationInfo&gt;</returns>
        public ApiResponse< List<ApiClientEvaluationInfo> > GetApiV2ClientEvaluationListWithHttpInfo (string session = null)
        {

            var localVarPath = "/api/v2/client/evaluation/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (session != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "session", session)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2ClientEvaluationList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ApiClientEvaluationInfo>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<ApiClientEvaluationInfo>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ApiClientEvaluationInfo>)));
        }

        /// <summary>
        /// Lists an overview of all evaluation runs visible to the current client. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>Task of List&lt;ApiClientEvaluationInfo&gt;</returns>
        public async System.Threading.Tasks.Task<List<ApiClientEvaluationInfo>> GetApiV2ClientEvaluationListAsync (string session = null)
        {
             ApiResponse<List<ApiClientEvaluationInfo>> localVarResponse = await GetApiV2ClientEvaluationListAsyncWithHttpInfo(session);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Lists an overview of all evaluation runs visible to the current client. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;ApiClientEvaluationInfo&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ApiClientEvaluationInfo>>> GetApiV2ClientEvaluationListAsyncWithHttpInfo (string session = null)
        {

            var localVarPath = "/api/v2/client/evaluation/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (session != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "session", session)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2ClientEvaluationList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ApiClientEvaluationInfo>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<ApiClientEvaluationInfo>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ApiClientEvaluationInfo>)));
        }

    }
}
