/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IEvaluationApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Returns basic information about a specific evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>ApiEvaluationInfo</returns>
        ApiEvaluationInfo GetApiV2EvaluationByEvaluationIdInfo (string evaluationId);

        /// <summary>
        /// Returns basic information about a specific evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>ApiResponse of ApiEvaluationInfo</returns>
        ApiResponse<ApiEvaluationInfo> GetApiV2EvaluationByEvaluationIdInfoWithHttpInfo (string evaluationId);
        /// <summary>
        /// Returns the state of a specific evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>ApiEvaluationState</returns>
        ApiEvaluationState GetApiV2EvaluationByEvaluationIdState (string evaluationId);

        /// <summary>
        /// Returns the state of a specific evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>ApiResponse of ApiEvaluationState</returns>
        ApiResponse<ApiEvaluationState> GetApiV2EvaluationByEvaluationIdStateWithHttpInfo (string evaluationId);
        /// <summary>
        /// Lists an overview of all evaluations visible to the current user.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ApiEvaluationInfo&gt;</returns>
        List<ApiEvaluationInfo> GetApiV2EvaluationInfoList ();

        /// <summary>
        /// Lists an overview of all evaluations visible to the current user.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ApiEvaluationInfo&gt;</returns>
        ApiResponse<List<ApiEvaluationInfo>> GetApiV2EvaluationInfoListWithHttpInfo ();
        /// <summary>
        /// Lists an overview of all evaluation visible to the current user.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ApiEvaluationState&gt;</returns>
        List<ApiEvaluationState> GetApiV2EvaluationStateList ();

        /// <summary>
        /// Lists an overview of all evaluation visible to the current user.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ApiEvaluationState&gt;</returns>
        ApiResponse<List<ApiEvaluationState>> GetApiV2EvaluationStateListWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Returns basic information about a specific evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>Task of ApiEvaluationInfo</returns>
        System.Threading.Tasks.Task<ApiEvaluationInfo> GetApiV2EvaluationByEvaluationIdInfoAsync (string evaluationId);

        /// <summary>
        /// Returns basic information about a specific evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>Task of ApiResponse (ApiEvaluationInfo)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiEvaluationInfo>> GetApiV2EvaluationByEvaluationIdInfoAsyncWithHttpInfo (string evaluationId);
        /// <summary>
        /// Returns the state of a specific evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>Task of ApiEvaluationState</returns>
        System.Threading.Tasks.Task<ApiEvaluationState> GetApiV2EvaluationByEvaluationIdStateAsync (string evaluationId);

        /// <summary>
        /// Returns the state of a specific evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>Task of ApiResponse (ApiEvaluationState)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiEvaluationState>> GetApiV2EvaluationByEvaluationIdStateAsyncWithHttpInfo (string evaluationId);
        /// <summary>
        /// Lists an overview of all evaluations visible to the current user.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;ApiEvaluationInfo&gt;</returns>
        System.Threading.Tasks.Task<List<ApiEvaluationInfo>> GetApiV2EvaluationInfoListAsync ();

        /// <summary>
        /// Lists an overview of all evaluations visible to the current user.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;ApiEvaluationInfo&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ApiEvaluationInfo>>> GetApiV2EvaluationInfoListAsyncWithHttpInfo ();
        /// <summary>
        /// Lists an overview of all evaluation visible to the current user.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;ApiEvaluationState&gt;</returns>
        System.Threading.Tasks.Task<List<ApiEvaluationState>> GetApiV2EvaluationStateListAsync ();

        /// <summary>
        /// Lists an overview of all evaluation visible to the current user.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;ApiEvaluationState&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ApiEvaluationState>>> GetApiV2EvaluationStateListAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class EvaluationApi : IEvaluationApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EvaluationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EvaluationApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EvaluationApi"/> class
        /// </summary>
        /// <returns></returns>
        public EvaluationApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EvaluationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EvaluationApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Returns basic information about a specific evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>ApiEvaluationInfo</returns>
        public ApiEvaluationInfo GetApiV2EvaluationByEvaluationIdInfo (string evaluationId)
        {
             ApiResponse<ApiEvaluationInfo> localVarResponse = GetApiV2EvaluationByEvaluationIdInfoWithHttpInfo(evaluationId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns basic information about a specific evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>ApiResponse of ApiEvaluationInfo</returns>
        public ApiResponse< ApiEvaluationInfo > GetApiV2EvaluationByEvaluationIdInfoWithHttpInfo (string evaluationId)
        {
            // verify the required parameter 'evaluationId' is set
            if (evaluationId == null)
                throw new ApiException(400, "Missing required parameter 'evaluationId' when calling EvaluationApi->GetApiV2EvaluationByEvaluationIdInfo");

            var localVarPath = "/api/v2/evaluation/{evaluationId}/info";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (evaluationId != null) localVarPathParams.Add("evaluationId", this.Configuration.ApiClient.ParameterToString(evaluationId)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2EvaluationByEvaluationIdInfo", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiEvaluationInfo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiEvaluationInfo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiEvaluationInfo)));
        }

        /// <summary>
        /// Returns basic information about a specific evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>Task of ApiEvaluationInfo</returns>
        public async System.Threading.Tasks.Task<ApiEvaluationInfo> GetApiV2EvaluationByEvaluationIdInfoAsync (string evaluationId)
        {
             ApiResponse<ApiEvaluationInfo> localVarResponse = await GetApiV2EvaluationByEvaluationIdInfoAsyncWithHttpInfo(evaluationId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns basic information about a specific evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>Task of ApiResponse (ApiEvaluationInfo)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiEvaluationInfo>> GetApiV2EvaluationByEvaluationIdInfoAsyncWithHttpInfo (string evaluationId)
        {
            // verify the required parameter 'evaluationId' is set
            if (evaluationId == null)
                throw new ApiException(400, "Missing required parameter 'evaluationId' when calling EvaluationApi->GetApiV2EvaluationByEvaluationIdInfo");

            var localVarPath = "/api/v2/evaluation/{evaluationId}/info";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (evaluationId != null) localVarPathParams.Add("evaluationId", this.Configuration.ApiClient.ParameterToString(evaluationId)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2EvaluationByEvaluationIdInfo", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiEvaluationInfo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiEvaluationInfo) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiEvaluationInfo)));
        }

        /// <summary>
        /// Returns the state of a specific evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>ApiEvaluationState</returns>
        public ApiEvaluationState GetApiV2EvaluationByEvaluationIdState (string evaluationId)
        {
             ApiResponse<ApiEvaluationState> localVarResponse = GetApiV2EvaluationByEvaluationIdStateWithHttpInfo(evaluationId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Returns the state of a specific evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>ApiResponse of ApiEvaluationState</returns>
        public ApiResponse< ApiEvaluationState > GetApiV2EvaluationByEvaluationIdStateWithHttpInfo (string evaluationId)
        {
            // verify the required parameter 'evaluationId' is set
            if (evaluationId == null)
                throw new ApiException(400, "Missing required parameter 'evaluationId' when calling EvaluationApi->GetApiV2EvaluationByEvaluationIdState");

            var localVarPath = "/api/v2/evaluation/{evaluationId}/state";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (evaluationId != null) localVarPathParams.Add("evaluationId", this.Configuration.ApiClient.ParameterToString(evaluationId)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2EvaluationByEvaluationIdState", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiEvaluationState>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiEvaluationState) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiEvaluationState)));
        }

        /// <summary>
        /// Returns the state of a specific evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>Task of ApiEvaluationState</returns>
        public async System.Threading.Tasks.Task<ApiEvaluationState> GetApiV2EvaluationByEvaluationIdStateAsync (string evaluationId)
        {
             ApiResponse<ApiEvaluationState> localVarResponse = await GetApiV2EvaluationByEvaluationIdStateAsyncWithHttpInfo(evaluationId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Returns the state of a specific evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <returns>Task of ApiResponse (ApiEvaluationState)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiEvaluationState>> GetApiV2EvaluationByEvaluationIdStateAsyncWithHttpInfo (string evaluationId)
        {
            // verify the required parameter 'evaluationId' is set
            if (evaluationId == null)
                throw new ApiException(400, "Missing required parameter 'evaluationId' when calling EvaluationApi->GetApiV2EvaluationByEvaluationIdState");

            var localVarPath = "/api/v2/evaluation/{evaluationId}/state";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (evaluationId != null) localVarPathParams.Add("evaluationId", this.Configuration.ApiClient.ParameterToString(evaluationId)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2EvaluationByEvaluationIdState", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiEvaluationState>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiEvaluationState) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiEvaluationState)));
        }

        /// <summary>
        /// Lists an overview of all evaluations visible to the current user. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ApiEvaluationInfo&gt;</returns>
        public List<ApiEvaluationInfo> GetApiV2EvaluationInfoList ()
        {
             ApiResponse<List<ApiEvaluationInfo>> localVarResponse = GetApiV2EvaluationInfoListWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Lists an overview of all evaluations visible to the current user. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ApiEvaluationInfo&gt;</returns>
        public ApiResponse< List<ApiEvaluationInfo> > GetApiV2EvaluationInfoListWithHttpInfo ()
        {

            var localVarPath = "/api/v2/evaluation/info/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2EvaluationInfoList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ApiEvaluationInfo>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<ApiEvaluationInfo>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ApiEvaluationInfo>)));
        }

        /// <summary>
        /// Lists an overview of all evaluations visible to the current user. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;ApiEvaluationInfo&gt;</returns>
        public async System.Threading.Tasks.Task<List<ApiEvaluationInfo>> GetApiV2EvaluationInfoListAsync ()
        {
             ApiResponse<List<ApiEvaluationInfo>> localVarResponse = await GetApiV2EvaluationInfoListAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Lists an overview of all evaluations visible to the current user. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;ApiEvaluationInfo&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ApiEvaluationInfo>>> GetApiV2EvaluationInfoListAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/v2/evaluation/info/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2EvaluationInfoList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ApiEvaluationInfo>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<ApiEvaluationInfo>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ApiEvaluationInfo>)));
        }

        /// <summary>
        /// Lists an overview of all evaluation visible to the current user. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;ApiEvaluationState&gt;</returns>
        public List<ApiEvaluationState> GetApiV2EvaluationStateList ()
        {
             ApiResponse<List<ApiEvaluationState>> localVarResponse = GetApiV2EvaluationStateListWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Lists an overview of all evaluation visible to the current user. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;ApiEvaluationState&gt;</returns>
        public ApiResponse< List<ApiEvaluationState> > GetApiV2EvaluationStateListWithHttpInfo ()
        {

            var localVarPath = "/api/v2/evaluation/state/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2EvaluationStateList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ApiEvaluationState>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<ApiEvaluationState>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ApiEvaluationState>)));
        }

        /// <summary>
        /// Lists an overview of all evaluation visible to the current user. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;ApiEvaluationState&gt;</returns>
        public async System.Threading.Tasks.Task<List<ApiEvaluationState>> GetApiV2EvaluationStateListAsync ()
        {
             ApiResponse<List<ApiEvaluationState>> localVarResponse = await GetApiV2EvaluationStateListAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Lists an overview of all evaluation visible to the current user. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;ApiEvaluationState&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ApiEvaluationState>>> GetApiV2EvaluationStateListAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/v2/evaluation/state/list";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetApiV2EvaluationStateList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ApiEvaluationState>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<ApiEvaluationState>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ApiEvaluationState>)));
        }

    }
}
