/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface ILogApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Accepts query logs from participants for the specified evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>SuccessStatus</returns>
        SuccessStatus PostApiV2LogQueryByEvaluationId (string session, string evaluationId, QueryEventLog body = null);

        /// <summary>
        /// Accepts query logs from participants for the specified evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of SuccessStatus</returns>
        ApiResponse<SuccessStatus> PostApiV2LogQueryByEvaluationIdWithHttpInfo (string session, string evaluationId, QueryEventLog body = null);
        /// <summary>
        /// Accepts result logs from participants  for the specified evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>SuccessStatus</returns>
        SuccessStatus PostApiV2LogResultByEvaluationId (string session, string evaluationId, QueryResultLog body = null);

        /// <summary>
        /// Accepts result logs from participants  for the specified evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of SuccessStatus</returns>
        ApiResponse<SuccessStatus> PostApiV2LogResultByEvaluationIdWithHttpInfo (string session, string evaluationId, QueryResultLog body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Accepts query logs from participants for the specified evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of SuccessStatus</returns>
        System.Threading.Tasks.Task<SuccessStatus> PostApiV2LogQueryByEvaluationIdAsync (string session, string evaluationId, QueryEventLog body = null);

        /// <summary>
        /// Accepts query logs from participants for the specified evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (SuccessStatus)</returns>
        System.Threading.Tasks.Task<ApiResponse<SuccessStatus>> PostApiV2LogQueryByEvaluationIdAsyncWithHttpInfo (string session, string evaluationId, QueryEventLog body = null);
        /// <summary>
        /// Accepts result logs from participants  for the specified evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of SuccessStatus</returns>
        System.Threading.Tasks.Task<SuccessStatus> PostApiV2LogResultByEvaluationIdAsync (string session, string evaluationId, QueryResultLog body = null);

        /// <summary>
        /// Accepts result logs from participants  for the specified evaluation.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (SuccessStatus)</returns>
        System.Threading.Tasks.Task<ApiResponse<SuccessStatus>> PostApiV2LogResultByEvaluationIdAsyncWithHttpInfo (string session, string evaluationId, QueryResultLog body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class LogApi : ILogApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LogApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LogApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LogApi"/> class
        /// </summary>
        /// <returns></returns>
        public LogApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LogApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LogApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Accepts query logs from participants for the specified evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>SuccessStatus</returns>
        public SuccessStatus PostApiV2LogQueryByEvaluationId (string session, string evaluationId, QueryEventLog body = null)
        {
             ApiResponse<SuccessStatus> localVarResponse = PostApiV2LogQueryByEvaluationIdWithHttpInfo(session, evaluationId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Accepts query logs from participants for the specified evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of SuccessStatus</returns>
        public ApiResponse< SuccessStatus > PostApiV2LogQueryByEvaluationIdWithHttpInfo (string session, string evaluationId, QueryEventLog body = null)
        {
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling LogApi->PostApiV2LogQueryByEvaluationId");
            // verify the required parameter 'evaluationId' is set
            if (evaluationId == null)
                throw new ApiException(400, "Missing required parameter 'evaluationId' when calling LogApi->PostApiV2LogQueryByEvaluationId");

            var localVarPath = "/api/v2/log/query/{evaluationId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (evaluationId != null) localVarPathParams.Add("evaluationId", this.Configuration.ApiClient.ParameterToString(evaluationId)); // path parameter
            if (session != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "session", session)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostApiV2LogQueryByEvaluationId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessStatus>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessStatus) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessStatus)));
        }

        /// <summary>
        /// Accepts query logs from participants for the specified evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of SuccessStatus</returns>
        public async System.Threading.Tasks.Task<SuccessStatus> PostApiV2LogQueryByEvaluationIdAsync (string session, string evaluationId, QueryEventLog body = null)
        {
             ApiResponse<SuccessStatus> localVarResponse = await PostApiV2LogQueryByEvaluationIdAsyncWithHttpInfo(session, evaluationId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Accepts query logs from participants for the specified evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (SuccessStatus)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SuccessStatus>> PostApiV2LogQueryByEvaluationIdAsyncWithHttpInfo (string session, string evaluationId, QueryEventLog body = null)
        {
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling LogApi->PostApiV2LogQueryByEvaluationId");
            // verify the required parameter 'evaluationId' is set
            if (evaluationId == null)
                throw new ApiException(400, "Missing required parameter 'evaluationId' when calling LogApi->PostApiV2LogQueryByEvaluationId");

            var localVarPath = "/api/v2/log/query/{evaluationId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (evaluationId != null) localVarPathParams.Add("evaluationId", this.Configuration.ApiClient.ParameterToString(evaluationId)); // path parameter
            if (session != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "session", session)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostApiV2LogQueryByEvaluationId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessStatus>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessStatus) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessStatus)));
        }

        /// <summary>
        /// Accepts result logs from participants  for the specified evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>SuccessStatus</returns>
        public SuccessStatus PostApiV2LogResultByEvaluationId (string session, string evaluationId, QueryResultLog body = null)
        {
             ApiResponse<SuccessStatus> localVarResponse = PostApiV2LogResultByEvaluationIdWithHttpInfo(session, evaluationId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Accepts result logs from participants  for the specified evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of SuccessStatus</returns>
        public ApiResponse< SuccessStatus > PostApiV2LogResultByEvaluationIdWithHttpInfo (string session, string evaluationId, QueryResultLog body = null)
        {
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling LogApi->PostApiV2LogResultByEvaluationId");
            // verify the required parameter 'evaluationId' is set
            if (evaluationId == null)
                throw new ApiException(400, "Missing required parameter 'evaluationId' when calling LogApi->PostApiV2LogResultByEvaluationId");

            var localVarPath = "/api/v2/log/result/{evaluationId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (evaluationId != null) localVarPathParams.Add("evaluationId", this.Configuration.ApiClient.ParameterToString(evaluationId)); // path parameter
            if (session != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "session", session)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostApiV2LogResultByEvaluationId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessStatus>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessStatus) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessStatus)));
        }

        /// <summary>
        /// Accepts result logs from participants  for the specified evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of SuccessStatus</returns>
        public async System.Threading.Tasks.Task<SuccessStatus> PostApiV2LogResultByEvaluationIdAsync (string session, string evaluationId, QueryResultLog body = null)
        {
             ApiResponse<SuccessStatus> localVarResponse = await PostApiV2LogResultByEvaluationIdAsyncWithHttpInfo(session, evaluationId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Accepts result logs from participants  for the specified evaluation. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="session">Session Token</param>
        /// <param name="evaluationId">The evaluation ID.</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (SuccessStatus)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SuccessStatus>> PostApiV2LogResultByEvaluationIdAsyncWithHttpInfo (string session, string evaluationId, QueryResultLog body = null)
        {
            // verify the required parameter 'session' is set
            if (session == null)
                throw new ApiException(400, "Missing required parameter 'session' when calling LogApi->PostApiV2LogResultByEvaluationId");
            // verify the required parameter 'evaluationId' is set
            if (evaluationId == null)
                throw new ApiException(400, "Missing required parameter 'evaluationId' when calling LogApi->PostApiV2LogResultByEvaluationId");

            var localVarPath = "/api/v2/log/result/{evaluationId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (evaluationId != null) localVarPathParams.Add("evaluationId", this.Configuration.ApiClient.ParameterToString(evaluationId)); // path parameter
            if (session != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "session", session)); // query parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PostApiV2LogResultByEvaluationId", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SuccessStatus>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (SuccessStatus) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(SuccessStatus)));
        }

    }
}
