/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// ApiClientAnswer
    /// </summary>
    [DataContract]
        public partial class ApiClientAnswer :  IEquatable<ApiClientAnswer>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiClientAnswer" /> class.
        /// </summary>
        /// <param name="text">text.</param>
        /// <param name="mediaItemName">mediaItemName.</param>
        /// <param name="mediaItemCollectionName">mediaItemCollectionName.</param>
        /// <param name="start">start.</param>
        /// <param name="end">end.</param>
        public ApiClientAnswer(string text = default(string), string mediaItemName = default(string), string mediaItemCollectionName = default(string), long? start = default(long?), long? end = default(long?))
        {
            this.Text = text;
            this.MediaItemName = mediaItemName;
            this.MediaItemCollectionName = mediaItemCollectionName;
            this.Start = start;
            this.End = end;
        }
        
        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets MediaItemName
        /// </summary>
        [DataMember(Name="mediaItemName", EmitDefaultValue=false)]
        public string MediaItemName { get; set; }

        /// <summary>
        /// Gets or Sets MediaItemCollectionName
        /// </summary>
        [DataMember(Name="mediaItemCollectionName", EmitDefaultValue=false)]
        public string MediaItemCollectionName { get; set; }

        /// <summary>
        /// Gets or Sets Start
        /// </summary>
        [DataMember(Name="start", EmitDefaultValue=false)]
        public long? Start { get; set; }

        /// <summary>
        /// Gets or Sets End
        /// </summary>
        [DataMember(Name="end", EmitDefaultValue=false)]
        public long? End { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiClientAnswer {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  MediaItemName: ").Append(MediaItemName).Append("\n");
            sb.Append("  MediaItemCollectionName: ").Append(MediaItemCollectionName).Append("\n");
            sb.Append("  Start: ").Append(Start).Append("\n");
            sb.Append("  End: ").Append(End).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiClientAnswer);
        }

        /// <summary>
        /// Returns true if ApiClientAnswer instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiClientAnswer to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiClientAnswer input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                ) && 
                (
                    this.MediaItemName == input.MediaItemName ||
                    (this.MediaItemName != null &&
                    this.MediaItemName.Equals(input.MediaItemName))
                ) && 
                (
                    this.MediaItemCollectionName == input.MediaItemCollectionName ||
                    (this.MediaItemCollectionName != null &&
                    this.MediaItemCollectionName.Equals(input.MediaItemCollectionName))
                ) && 
                (
                    this.Start == input.Start ||
                    (this.Start != null &&
                    this.Start.Equals(input.Start))
                ) && 
                (
                    this.End == input.End ||
                    (this.End != null &&
                    this.End.Equals(input.End))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                if (this.MediaItemName != null)
                    hashCode = hashCode * 59 + this.MediaItemName.GetHashCode();
                if (this.MediaItemCollectionName != null)
                    hashCode = hashCode * 59 + this.MediaItemCollectionName.GetHashCode();
                if (this.Start != null)
                    hashCode = hashCode * 59 + this.Start.GetHashCode();
                if (this.End != null)
                    hashCode = hashCode * 59 + this.End.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
