/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// ApiEvaluationOverview
    /// </summary>
    [DataContract]
        public partial class ApiEvaluationOverview :  IEquatable<ApiEvaluationOverview>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiEvaluationOverview" /> class.
        /// </summary>
        /// <param name="state">state (required).</param>
        /// <param name="teamOverviews">teamOverviews (required).</param>
        public ApiEvaluationOverview(RunManagerStatus state = default(RunManagerStatus), List<ApiTeamTaskOverview> teamOverviews = default(List<ApiTeamTaskOverview>))
        {
            // to ensure "state" is required (not null)
            if (state == null)
            {
                throw new InvalidDataException("state is a required property for ApiEvaluationOverview and cannot be null");
            }
            else
            {
                this.State = state;
            }
            // to ensure "teamOverviews" is required (not null)
            if (teamOverviews == null)
            {
                throw new InvalidDataException("teamOverviews is a required property for ApiEvaluationOverview and cannot be null");
            }
            else
            {
                this.TeamOverviews = teamOverviews;
            }
        }
        
        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public RunManagerStatus State { get; set; }

        /// <summary>
        /// Gets or Sets TeamOverviews
        /// </summary>
        [DataMember(Name="teamOverviews", EmitDefaultValue=false)]
        public List<ApiTeamTaskOverview> TeamOverviews { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiEvaluationOverview {\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  TeamOverviews: ").Append(TeamOverviews).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiEvaluationOverview);
        }

        /// <summary>
        /// Returns true if ApiEvaluationOverview instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiEvaluationOverview to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiEvaluationOverview input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.TeamOverviews == input.TeamOverviews ||
                    this.TeamOverviews != null &&
                    input.TeamOverviews != null &&
                    this.TeamOverviews.SequenceEqual(input.TeamOverviews)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                if (this.TeamOverviews != null)
                    hashCode = hashCode * 59 + this.TeamOverviews.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
