/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// ApiSubmissionInfo
    /// </summary>
    [DataContract]
        public partial class ApiSubmissionInfo :  IEquatable<ApiSubmissionInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiSubmissionInfo" /> class.
        /// </summary>
        /// <param name="evaluationId">evaluationId (required).</param>
        /// <param name="taskId">taskId (required).</param>
        /// <param name="submissions">submissions (required).</param>
        public ApiSubmissionInfo(string evaluationId = default(string), string taskId = default(string), List<ApiSubmission> submissions = default(List<ApiSubmission>))
        {
            // to ensure "evaluationId" is required (not null)
            if (evaluationId == null)
            {
                throw new InvalidDataException("evaluationId is a required property for ApiSubmissionInfo and cannot be null");
            }
            else
            {
                this.EvaluationId = evaluationId;
            }
            // to ensure "taskId" is required (not null)
            if (taskId == null)
            {
                throw new InvalidDataException("taskId is a required property for ApiSubmissionInfo and cannot be null");
            }
            else
            {
                this.TaskId = taskId;
            }
            // to ensure "submissions" is required (not null)
            if (submissions == null)
            {
                throw new InvalidDataException("submissions is a required property for ApiSubmissionInfo and cannot be null");
            }
            else
            {
                this.Submissions = submissions;
            }
        }
        
        /// <summary>
        /// Gets or Sets EvaluationId
        /// </summary>
        [DataMember(Name="evaluationId", EmitDefaultValue=false)]
        public string EvaluationId { get; set; }

        /// <summary>
        /// Gets or Sets TaskId
        /// </summary>
        [DataMember(Name="taskId", EmitDefaultValue=false)]
        public string TaskId { get; set; }

        /// <summary>
        /// Gets or Sets Submissions
        /// </summary>
        [DataMember(Name="submissions", EmitDefaultValue=false)]
        public List<ApiSubmission> Submissions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApiSubmissionInfo {\n");
            sb.Append("  EvaluationId: ").Append(EvaluationId).Append("\n");
            sb.Append("  TaskId: ").Append(TaskId).Append("\n");
            sb.Append("  Submissions: ").Append(Submissions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ApiSubmissionInfo);
        }

        /// <summary>
        /// Returns true if ApiSubmissionInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of ApiSubmissionInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApiSubmissionInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EvaluationId == input.EvaluationId ||
                    (this.EvaluationId != null &&
                    this.EvaluationId.Equals(input.EvaluationId))
                ) && 
                (
                    this.TaskId == input.TaskId ||
                    (this.TaskId != null &&
                    this.TaskId.Equals(input.TaskId))
                ) && 
                (
                    this.Submissions == input.Submissions ||
                    this.Submissions != null &&
                    input.Submissions != null &&
                    this.Submissions.SequenceEqual(input.Submissions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EvaluationId != null)
                    hashCode = hashCode * 59 + this.EvaluationId.GetHashCode();
                if (this.TaskId != null)
                    hashCode = hashCode * 59 + this.TaskId.GetHashCode();
                if (this.Submissions != null)
                    hashCode = hashCode * 59 + this.Submissions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
