/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ApiSubmissionOption
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ApiSubmissionOption
    {
        /// <summary>
        /// Enum NODUPLICATES for value: NO_DUPLICATES
        /// </summary>
        [EnumMember(Value = "NO_DUPLICATES")]
        NODUPLICATES = 1,
        /// <summary>
        /// Enum LIMITCORRECTPERTEAM for value: LIMIT_CORRECT_PER_TEAM
        /// </summary>
        [EnumMember(Value = "LIMIT_CORRECT_PER_TEAM")]
        LIMITCORRECTPERTEAM = 2,
        /// <summary>
        /// Enum LIMITWRONGPERTEAM for value: LIMIT_WRONG_PER_TEAM
        /// </summary>
        [EnumMember(Value = "LIMIT_WRONG_PER_TEAM")]
        LIMITWRONGPERTEAM = 3,
        /// <summary>
        /// Enum LIMITTOTALPERTEAM for value: LIMIT_TOTAL_PER_TEAM
        /// </summary>
        [EnumMember(Value = "LIMIT_TOTAL_PER_TEAM")]
        LIMITTOTALPERTEAM = 4,
        /// <summary>
        /// Enum LIMITCORRECTPERMEMBER for value: LIMIT_CORRECT_PER_MEMBER
        /// </summary>
        [EnumMember(Value = "LIMIT_CORRECT_PER_MEMBER")]
        LIMITCORRECTPERMEMBER = 5,
        /// <summary>
        /// Enum TEMPORALSUBMISSION for value: TEMPORAL_SUBMISSION
        /// </summary>
        [EnumMember(Value = "TEMPORAL_SUBMISSION")]
        TEMPORALSUBMISSION = 6,
        /// <summary>
        /// Enum TEXTUALSUBMISSION for value: TEXTUAL_SUBMISSION
        /// </summary>
        [EnumMember(Value = "TEXTUAL_SUBMISSION")]
        TEXTUALSUBMISSION = 7,
        /// <summary>
        /// Enum ITEMSUBMISSION for value: ITEM_SUBMISSION
        /// </summary>
        [EnumMember(Value = "ITEM_SUBMISSION")]
        ITEMSUBMISSION = 8,
        /// <summary>
        /// Enum MINIMUMTIMEGAP for value: MINIMUM_TIME_GAP
        /// </summary>
        [EnumMember(Value = "MINIMUM_TIME_GAP")]
        MINIMUMTIMEGAP = 9    }
}
