/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ApiTaskOption
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ApiTaskOption
    {
        /// <summary>
        /// Enum HIDDENRESULTS for value: HIDDEN_RESULTS
        /// </summary>
        [EnumMember(Value = "HIDDEN_RESULTS")]
        HIDDENRESULTS = 1,
        /// <summary>
        /// Enum MAPTOSEGMENT for value: MAP_TO_SEGMENT
        /// </summary>
        [EnumMember(Value = "MAP_TO_SEGMENT")]
        MAPTOSEGMENT = 2,
        /// <summary>
        /// Enum PROLONGONSUBMISSION for value: PROLONG_ON_SUBMISSION
        /// </summary>
        [EnumMember(Value = "PROLONG_ON_SUBMISSION")]
        PROLONGONSUBMISSION = 3    }
}
