/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ApiTargetType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ApiTargetType
    {
        /// <summary>
        /// Enum JUDGEMENT for value: JUDGEMENT
        /// </summary>
        [EnumMember(Value = "JUDGEMENT")]
        JUDGEMENT = 1,
        /// <summary>
        /// Enum JUDGEMENTWITHVOTE for value: JUDGEMENT_WITH_VOTE
        /// </summary>
        [EnumMember(Value = "JUDGEMENT_WITH_VOTE")]
        JUDGEMENTWITHVOTE = 2,
        /// <summary>
        /// Enum MEDIAITEM for value: MEDIA_ITEM
        /// </summary>
        [EnumMember(Value = "MEDIA_ITEM")]
        MEDIAITEM = 3,
        /// <summary>
        /// Enum MEDIAITEMTEMPORALRANGE for value: MEDIA_ITEM_TEMPORAL_RANGE
        /// </summary>
        [EnumMember(Value = "MEDIA_ITEM_TEMPORAL_RANGE")]
        MEDIAITEMTEMPORALRANGE = 4,
        /// <summary>
        /// Enum TEXT for value: TEXT
        /// </summary>
        [EnumMember(Value = "TEXT")]
        TEXT = 5    }
}
