/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ApiTaskStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ApiTaskStatus
    {
        /// <summary>
        /// Enum NOTASK for value: NO_TASK
        /// </summary>
        [EnumMember(Value = "NO_TASK")]
        NOTASK = 1,
        /// <summary>
        /// Enum CREATED for value: CREATED
        /// </summary>
        [EnumMember(Value = "CREATED")]
        CREATED = 2,
        /// <summary>
        /// Enum PREPARING for value: PREPARING
        /// </summary>
        [EnumMember(Value = "PREPARING")]
        PREPARING = 3,
        /// <summary>
        /// Enum RUNNING for value: RUNNING
        /// </summary>
        [EnumMember(Value = "RUNNING")]
        RUNNING = 4,
        /// <summary>
        /// Enum ENDED for value: ENDED
        /// </summary>
        [EnumMember(Value = "ENDED")]
        ENDED = 5,
        /// <summary>
        /// Enum IGNORED for value: IGNORED
        /// </summary>
        [EnumMember(Value = "IGNORED")]
        IGNORED = 6    }
}
