/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ApiTargetOption
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ApiTargetOption
    {
        /// <summary>
        /// Enum SINGLEMEDIAITEM for value: SINGLE_MEDIA_ITEM
        /// </summary>
        [EnumMember(Value = "SINGLE_MEDIA_ITEM")]
        SINGLEMEDIAITEM = 1,
        /// <summary>
        /// Enum SINGLEMEDIASEGMENT for value: SINGLE_MEDIA_SEGMENT
        /// </summary>
        [EnumMember(Value = "SINGLE_MEDIA_SEGMENT")]
        SINGLEMEDIASEGMENT = 2,
        /// <summary>
        /// Enum JUDGEMENT for value: JUDGEMENT
        /// </summary>
        [EnumMember(Value = "JUDGEMENT")]
        JUDGEMENT = 3,
        /// <summary>
        /// Enum VOTE for value: VOTE
        /// </summary>
        [EnumMember(Value = "VOTE")]
        VOTE = 4,
        /// <summary>
        /// Enum TEXT for value: TEXT
        /// </summary>
        [EnumMember(Value = "TEXT")]
        TEXT = 5    }
}
