/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ApiTemporalUnit
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ApiTemporalUnit
    {
        /// <summary>
        /// Enum FRAMENUMBER for value: FRAME_NUMBER
        /// </summary>
        [EnumMember(Value = "FRAME_NUMBER")]
        FRAMENUMBER = 1,
        /// <summary>
        /// Enum SECONDS for value: SECONDS
        /// </summary>
        [EnumMember(Value = "SECONDS")]
        SECONDS = 2,
        /// <summary>
        /// Enum MILLISECONDS for value: MILLISECONDS
        /// </summary>
        [EnumMember(Value = "MILLISECONDS")]
        MILLISECONDS = 3,
        /// <summary>
        /// Enum TIMECODE for value: TIMECODE
        /// </summary>
        [EnumMember(Value = "TIMECODE")]
        TIMECODE = 4    }
}
