/* 
 * DRES Client API
 *
 * Client API for DRES (Distributed Retrieval Evaluation Server), Version 2.0.0-RC4
 *
 * OpenAPI spec version: 2.0.0-RC4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ApiVerdictStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ApiVerdictStatus
    {
        /// <summary>
        /// Enum CORRECT for value: CORRECT
        /// </summary>
        [EnumMember(Value = "CORRECT")]
        CORRECT = 1,
        /// <summary>
        /// Enum WRONG for value: WRONG
        /// </summary>
        [EnumMember(Value = "WRONG")]
        WRONG = 2,
        /// <summary>
        /// Enum INDETERMINATE for value: INDETERMINATE
        /// </summary>
        [EnumMember(Value = "INDETERMINATE")]
        INDETERMINATE = 3,
        /// <summary>
        /// Enum UNDECIDABLE for value: UNDECIDABLE
        /// </summary>
        [EnumMember(Value = "UNDECIDABLE")]
        UNDECIDABLE = 4    }
}
